import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  weight: ['400', '500', '700'], // Escolha os pesos que você usa (regular, medium, bold)
  subsets: ['latin'], // Geralmente 'latin' para português
  display: 'swap', // Garante que o texto seja visível durante o carregamento da fonte
  variable: '--font-roboto', // Opcional: para usar como variável CSS
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} ${roboto.variable} overflow-x-hidden-wrapper`}
      >
        {children}
      </body>
    </html>
  );
}
